/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    {
      pattern: /text-(.*)/,
    },
  ],
  theme: {
    extend: {
      fontFamily: {
        uber: ["UberMove", "sans-serif"],
        uberText: ["UberMoveText", "sans-serif"],
        outfit: ["Outfit", "sans-serif"],
      },
      colors: {
        background: "var(--dml-color-background)",
        foreground: "var(--dml-color-foreground)",
        v2foreground: {
          DEFAULT: "var(--dml-color-v2foreground)",
          50: "var(--dml-color-v2foreground-50)",
          100: "var(--dml-color-v2foreground-100)",
          200: "var(--dml-color-v2foreground-200)",
          300: "var(--dml-color-v2foreground-300)",
          400: "var(--dml-color-v2foreground-400)",
          500: "var(--dml-color-v2foreground-500)",
          600: "var(--dml-color-v2foreground-600)",
          700: "var(--dml-color-v2foreground-700)",
          800: "var(--dml-color-v2foreground-800)",
          900: "var(--dml-color-v2foreground-900)",
        },
        "v2foreground-light": "var(--dml-color-v2foreground-light)",
        thrive: "var(--dml-color-thriveWell)",
        "foreground-3": "var(--dml-color-foreground-3)",
        "primary-hover": "var(--dml-color-hover-primary)",
        "foreground/80": "rgba(12,12,12,0.8)",
        primary: "var(--dml-color-primary)",
        v2primary: {
          DEFAULT: "var(--dml-color-v2primary)",
          50: "var(--dml-color-v2primary-50)",
          100: "var(--dml-color-v2primary-100)",
          200: "var(--dml-color-v2primary-200)",
          300: "var(--dml-color-v2primary-300)",
          400: "var(--dml-color-v2primary-400)",
          500: "var(--dml-color-v2primary-500)",
          600: "var(--dml-color-v2primary-600)",
          700: "var(--dml-color-v2primary-700)",
          800: "var(--dml-color-v2primary-800)",
          900: "var(--dml-color-v2primary-900)",
        },
        "primary-light": "var(--dml-color-primary-light)",
        secondary: "var(--dml-color-secondary)",
        danger: "var(--dml-color-danger)",
        "danger-light": "var(--dml-color-danger-light)",
        "danger-deep": "var(--dml-color-danger-deep)",
        "danger-badge": "var(--dml-color-danger-badge)",
        grey: "var(--dml-color-grey)",
        "grey-medium": "var(--dml-color-grey-medium)",
        "grey-btn": "var(--dml-color-grey-btn)",
        "grey-low": "var(--dml-color-grey-low)",
        v2grey: {
          DEFAULT: "var(--dml-color-v2grey)",
          50: "var(--dml-color-v2grey-50)",
          100: "var(--dml-color-v2grey-100)",
          200: "var(--dml-color-v2grey-200)",
          300: "var(--dml-color-v2grey-300)",
          400: "var(--dml-color-v2grey-400)",
          500: "var(--dml-color-v2grey-500)",
          600: "var(--dml-color-v2grey-600)",
          700: "var(--dml-color-v2grey-700)",
          800: "var(--dml-color-v2grey-800)",
          900: "var(--dml-color-v2grey-900)",
        },
        "grey-shade": "var(--dml-color-grey-shade)",
        "tag-bg": "var(--dml-color-tag-bg)",
        "tag-bg-deep": "var(--dml-color-tag-bg-deep)",
        "natural-white": "var(--dml-color-natural-white)",
        green: "var(--dml-color-green)",
        "green-low": "var(--dml-color-green-low)",
        "danger-medium": "var(--dml-color-danger-medium)",
        purple: "var(--dml-color-purple)",
        v2purple: {
          DEFAULT: "var(--dml-color-v2purple)",
          50: "var(--dml-color-v2purple-50)",
          100: "var(--dml-color-v2purple-100)",
          200: "var(--dml-color-v2purple-200)",
          300: "var(--dml-color-v2purple-300)",
          400: "var(--dml-color-v2purple-400)",
          500: "var(--dml-color-v2purple-500)",
          600: "var(--dml-color-v2purple-600)",
          700: "var(--dml-color-v2purple-700)",
          800: "var(--dml-color-v2purple-800)",
          900: "var(--dml-color-v2purple-900)",
        },
        "purple-extra-light": "var(--dml-color-purple-extra-light)",
        "purple-light": "var(--dml-color-purple-light)",
        "purple-medium": "var(--dml-color-purple-medium)",
        "purple-deep": "var(--dml-color-purple-deep)",
        "she-purple": "var(--dml-color-she-purple)",
        "red-light": "var(--dml-color-red-light)",
        "red-medium": "var(--dml-color-red-medium)",
        "red-deep": "var(--dml-color-red-deep)",
        "yellow-light": "var(--dml-color-yellow-light)",
        "yellow-medium": "var(--dml-color-yellow-medium)",
        "yellow-deep": "var(--dml-color-yellow-deep)",
        "green-extra-light": "var(--dml-color-green-extra-light)",
        "green-light": "var(--dml-color-green-light)",
        "green-medium": "var(--dml-color-green-medium)",
        "green-middle": "var(--dml-color-green-middle)",
        "green-deep": "var(--dml-color-green-deep)",
        "blue-light": "var(--dml-color-blue-light)",
        "blue-medium": "var(--dml-color-blue-medium)",
        "blue-foam": "var(--dml-color-blue-foam)",
        "lily-white": "var(--dml-color-lily-white)",
        "titan-white": "var(--dml-color-titan-white)",
        "serenade-white": "var(--dml-color-serenade-white)",
        disabled: "var(--dml-color-disabled)",
        rose: "var(--dml-color-rose)",
        v2orange: {
          DEFAULT: "var(--dml-color-v2orange)",
          50: "var(--dml-color-v2orange-50)",
          100: "var(--dml-color-v2orange-100)",
          200: "var(--dml-color-v2orange-200)",
          300: "var(--dml-color-v2orange-300)",
          400: "var(--dml-color-v2orange-400)",
          500: "var(--dml-color-v2orange-500)",
          600: "var(--dml-color-v2orange-600)",
          700: "var(--dml-color-v2orange-700)",
          800: "var(--dml-color-v2orange-800)",
          900: "var(--dml-color-v2orange-900)",
        },
        v2cyan: {
          DEFAULT: "var(--dml-color-v2cyan)",
          50: "var(--dml-color-v2cyan-50)",
          100: "var(--dml-color-v2cyan-100)",
          200: "var(--dml-color-v2cyan-200)",
          300: "var(--dml-color-v2cyan-300)",
          400: "var(--dml-color-v2cyan-400)",
          500: "var(--dml-color-v2cyan-500)",
          600: "var(--dml-color-v2cyan-600)",
          700: "var(--dml-color-v2cyan-700)",
          800: "var(--dml-color-v2cyan-800)",
          900: "var(--dml-color-v2cyan-900)",
        },
        v2rose: {
          DEFAULT: "var(--dml-color-v2rose)",
          50: "var(--dml-color-v2rose-50)",
          100: "var(--dml-color-v2rose-100)",
          200: "var(--dml-color-v2rose-200)",
          300: "var(--dml-color-v2rose-300)",
          400: "var(--dml-color-v2rose-400)",
          500: "var(--dml-color-v2rose-500)",
          600: "var(--dml-color-v2rose-600)",
          700: "var(--dml-color-v2rose-700)",
          800: "var(--dml-color-v2rose-800)",
          900: "var(--dml-color-v2rose-900)",
        },

        v2apricot: {
          DEFAULT: "var(--dml-color-v2apricot)",
          50: "var(--dml-color-v2apricot-50)",
          100: "var(--dml-color-v2apricot-100)",
          200: "var(--dml-color-v2apricot-200)",
          300: "var(--dml-color-v2apricot-300)",
          400: "var(--dml-color-v2apricot-400)",
          500: "var(--dml-color-v2apricot-500)",
          600: "var(--dml-color-v2apricot-600)",
          700: "var(--dml-color-v2apricot-700)",
          800: "var(--dml-color-v2apricot-800)",
          900: "var(--dml-color-v2apricot-900)",
        },
        v2gold: {
          DEFAULT: "var(--dml-color-v2gold)",
          50: "var(--dml-color-v2gold-50)",
          100: "var(--dml-color-v2gold-100)",
          200: "var(--dml-color-v2gold-200)",
          300: "var(--dml-color-v2gold-300)",
          400: "var(--dml-color-v2gold-400)",
          500: "var(--dml-color-v2gold-500)",
          600: "var(--dml-color-v2gold-600)",
          700: "var(--dml-color-v2gold-700)",
          800: "var(--dml-color-v2gold-800)",
          900: "var(--dml-color-v2gold-900)",
        },
        v2lime: {
          DEFAULT: "var(--dml-color-v2lime)",
          50: "var(--dml-color-v2lime-50)",
          100: "var(--dml-color-v2lime-100)",
          200: "var(--dml-color-v2lime-200)",
          300: "var(--dml-color-v2lime-300)",
          400: "var(--dml-color-v2lime-400)",
          500: "var(--dml-color-v2lime-500)",
          600: "var(--dml-color-v2lime-600)",
          700: "var(--dml-color-v2lime-700)",
          800: "var(--dml-color-v2lime-800)",
          900: "var(--dml-color-v2lime-900)",
        },
        v2teal: {
          DEFAULT: "var(--dml-color-v2teal)",
          50: "var(--dml-color-v2teal-50)",
          100: "var(--dml-color-v2teal-100)",
          200: "var(--dml-color-v2teal-200)",
          300: "var(--dml-color-v2teal-300)",
          400: "var(--dml-color-v2teal-400)",
          500: "var(--dml-color-v2teal-500)",
          600: "var(--dml-color-v2teal-600)",
          700: "var(--dml-color-v2teal-700)",
          800: "var(--dml-color-v2teal-800)",
          900: "var(--dml-color-v2teal-900)",
        },
      },
      boxShadow: {
        "dml-box-shadow": "var(--dml-box-shadow)",
        "dml-v2box-shadow": "var(--dml-v2box-shadow)",
        "dml-v2box-shadow-light": "var(--dml-v2box-shadow-light)",
        "custom-dml-1": "var(--dml-box-shadow)",
        "custom-2": "var(--dml-dropdown-shadow)",
      },
      spacing: {
        "5px": "5px",
        4.5: "18px",
      },
      padding: {
        17: "17px",
      },
      backgroundImage: {
        "login-bg": "url('/images/login-bg.png')",
      },
      screens: {
        "max-xs": "350px",
        sm: "576px",
        md: "768px",
        lg: "992px",
        xl: "1280px",
        "2xl": "1360px",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: 0, transform: "translateY(20px)" },
          "100%": { opacity: 1, transform: "(0)" },
        },
        fadeInRight: {
          "0%": { opacity: 0, transform: "translateX(30px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: {
        fadeInUp: "fadeInUp 0.4s ease-out",
        fadeInRight: "fadeInRight 0.4s ease-out",
        "spin-slow": "spin 1.6s linear infinite",
      },
    },
  },
  plugins: [],
};
